### ISSUE TITLE
Отладка быстрой библиотеки XSL на C

### ISSUE THREAD

**Issue by ivan-ushakov** [Litres/turboxsl#2]
Привет.
Готов помочь с задачей "Отладка быстрой библиотеки XSL на C" (http://freelansim.ru/tasks/99543).

**Comment by gribuser** [comment]
Ок, будем иметь вас в виду.
Можно немного о вас, на какие условия вы рассчитываете?

**Comment by ivan-ushakov** [comment]
Мне интересно сделать первую часть задачи, и я считаю что моих знаний и опыта для этого достаточно. Со второй частью (интеграция с Perl) - не уверен. 
Условие простое: я исправляю проблемы первой части - вы платите, если я не справился - платить не нужно.

**Comment by gribuser** [comment]
Сколько денег хотите?

(пишите на gu@litres.ru)

**Comment by code-exchange** [comment]
Тоже зашёл оттуда просто посмотреть. Куда ни гляну, везде malloc(), realloc() без проверки возвращаемого значения на NULL.

**Comment by gribuser** [comment]
Оно падает не от того, что память кончается, если что. Т.е. то, что она при нехватке памяти свалится в кору вместо нормального сообщения об ошибке это, конечно, прискорбно, но это печалит нас в последнюю очередь т.к. среда исполнения для этого у нас имеет памяти заведомо больше, чем надо (если течь не будет).
